In [1]:
import numpy as np

In [2]:
#creating an array
arr=np.array((1,2,3,4,5,"utkarsh"))

In [3]:
arr

array(['1', '2', '3', '4', '5', 'utkarsh'], dtype='<U11')

In [4]:
#datatype  of an array
arr=np.array([1,2,3,4],dtype=float)

In [5]:
arr

array([1., 2., 3., 4.])

In [6]:
arr=np.arange(10,40,2)

In [7]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [8]:
np.insert(arr,5,50)

array([10, 12, 14, 16, 18, 50, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [9]:
np.delete(arr,5)

array([10, 12, 14, 16, 18, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [10]:
np.insert(arr,5,int(40))

array([10, 12, 14, 16, 18, 40, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [11]:
np.insert(arr,0,100)

array([100,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,
        34,  36,  38])

In [12]:
arr=np.append(arr,50)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 50])

In [13]:
#matrices


In [14]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [15]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
a=[i for i in range (10000000)]
b=[i for i in range (10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

2.865032196044922


In [17]:
arr1=np.arange(10000000)
arr2=np.arange(10000000,20000000)
import time
start=time.time()
arr3=arr1+arr2
print(time.time()-start)

0.04583263397216797


In [19]:
2.865032196044922/0.0458326339721679

62.5107472065587

In [20]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
mat[1,1]

6

In [23]:
d3=np.array([[ 1,2,3,4],[ 5,6,7,8],[ 9,10,11,12]])

In [24]:
d3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
for i in range(3):
    print(mat[i,1])

2
6
10


In [34]:
d3=np.array([[[1,2,3,4],[ 5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [35]:
d3[1,0]

array([ 9, 10, 11, 12])

In [36]:
d3[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])